### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/rrgc#4]
* [ ] analyse the strange behavior detected on zrwf + add a unit test
* [x] only print paths instead of deleting (#5)
* [x] add a flag to print the opposite list (`--keep`)
* [ ] add examples in the CLI help
* [ ] add `--glob` flag to specify if the paths should be matched or taken as they are + add examples in -help
* [ ] improve support of files with exact same timestamp
* [ ] support alternative way to get the date, i.e., by parsing the filename
